name: Integrity Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate new SHA256 checksums
        run: |
          mkdir -p .github
          # Generate hashes and remove 'sha256' prefix
          find . -type f -name "*.bat" -exec sha256sum {} \; | sed 's/^sha256://g' | sort > new_checksums.txt
          echo "Generated new checksums:"
          cat new_checksums.txt

      - name: Append new hashes if missing
        run: |
          if [ ! -f .github/checksums.txt ]; then
            echo "No existing checksums.txt found — creating baseline."
            cp new_checksums.txt .github/checksums.txt
          else
            echo "Comparing and appending new entries..."
            while IFS= read -r line; do
              file=$(echo "$line" | awk '{print $2}')
              if ! grep -q "$file" .github/checksums.txt; then
                echo "$line" >> .github/checksums.txt
                echo "Added new entry for: $file"
              fi
            done < new_checksums.txt
          fi

      - name: Show updated checksum file
        run: cat .github/checksums.txt

      - name: Commit updated checksums (if changed)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/checksums.txt
          if git diff --cached --quiet; then
            echo "No checksum changes detected."
          else
            git commit -m "Update checksums.txt (auto)"
            git push
          fi
