name: Integrity Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate checksums.txt
        run: |
          find . -type f -name "*.bat" -exec sha256sum {} \; | sort > checksums.txt
          echo "Generated checksums.txt:"
          cat checksums.txt

      - name: Compare with previous version
        id: compare
        run: |
          if [ -f .github/checksums.txt ]; then
            diff .github/checksums.txt checksums.txt > checksum_diff.txt || true
            if [ -s checksum_diff.txt ]; then
              echo "Differences found between commits:"
              cat checksum_diff.txt
              echo "result=fail" >> $GITHUB_OUTPUT
            else
              echo "No changes detected in .bat file integrity."
              echo "result=pass" >> $GITHUB_OUTPUT
            fi
          else
            echo "No previous checksums found — creating baseline."
            echo "result=baseline" >> $GITHUB_OUTPUT
          fi

      - name: Store baseline
        if: steps.compare.outputs.result == 'baseline' || steps.compare.outputs.result == 'pass'
        run: |
          mkdir -p .github
          cp checksums.txt .github/checksums.txt

      - name: Upload integrity logs
        uses: actions/upload-artifact@v4
        with:
          name: integrity-report
          path: |
            checksums.txt
            checksum_diff.txt

      - name: Fail if integrity mismatch
        if: steps.compare.outputs.result == 'fail'
        run: |
          echo "Integrity mismatch detected in one or more batch files."
          exit 1
